services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - PORT=3000
      - DB_PATH=/app/data/data.sqlite
    volumes:
      - app_data:/app/data
    restart: unless-stopped

volumes:
  app_data: